title = "gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Global allowlist"
paths = [
    '''pnpm-lock\.yaml$''',
    '''\.gitleaks\.toml$''',
    '''(?i)\.(jpg|jpeg|png|gif|svg|ico)$''',
    '''node_modules/''',
    '''dist/''',
    '''\.(claude)/''',
]
